### ISSUE TITLE
Error 3 / Last session not closed

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#98]
Just pulled latest commit, runned as usual.

got instant error
Error #:     3
Message:     File is in use.
Code:        copy file (This.cMainFolder + 'Source\CategoriesSource.dbf') to (This.cMainFolder + 'ProjectExplorerCategories.dbf')
Line #:      223
Method:      projectexplorerformdesktop_52F175XTZ.init

Choose Yes to display the debugger, No to continue without the debugger, or Cancel to cancel execution

There is a leftover datasession with this table in use.

**What I have done is:**
I found your messages
DO projectexplorer.app
MODI PROJ DEMO1.pjx &&_to a project in the solution_
Played around a bit
Closed projectexplorer.app
issued CLEAR ALL
git pull
DO projectexplorer.app

The leftover datasession passed after I've closed ProjectManager of Demo1.pjx
ProjectExplorer opens as expected.

I can reproduce this behaviour.

Edit:
The unknown datasesssion is there all the time after closing the ProjectExplorer. I need to kill all ProjectManagers of projects visible to delete it.

**Comment by DougHennig** [comment]
Fixed in the latest release.

**Comment by lscheffler** [comment]
The behaviour is better now, But still the unknown datasession is there, if I do
```
do projectexplorer.app
MODI PROJ Demo1.pjx
Close projectexplorer.
```
The datasession is now without open tables,  but it looks like projectexplorer is still not closed.
If I try to do something with git, for example reset to an other commit, I see that the app is blocked. I must issue CLEAR ALL

**Comment by DougHennig** [comment]
I can't reproduce that. I did those same steps and don't see any datasessions others than Default and Unknown(3) which is Thor's.

**Comment by lscheffler** [comment]
Ok, from scratch

Thor is not installed
solution and pjx is in e:\x
SET DEFA is to e:\x\data\y
I have a bunch of pjx, all located in e:\x, open. None is part of the solution
SET
do Projectexplorer.app
-navigate to e:\x\solution.xml in open dialog
modi proj e:\x\demo1.pjx, what is in solution
demo1 is now visible
press the close button of projectexplorer
unknown datasession (2)
close project demo1
datasession goes away.

**Comment by DougHennig** [comment]
Weird: I still can't reproduce it.

By the way, I'm on vacation for the next week so I won't respond to any issue until I return on December 4.

**Comment by DougHennig** [comment]
I went through those exact steps and still cannot reproduce this: when I close Project Explorer, the second datasession goes away and all of the projects that were open are still open. Closing the one that's in the solution doesn't change anything.

**Comment by lscheffler** [comment]
I have testet a bit more.

The problem occurs too, if one of the two projects in the solution is already open.
It is to be noted that both projects come with project hooks.

I also notice (project hooks output) that ProjectExplorer is opening the projct non open three times while it is opening the one already open two times.  Not good. My hooks stores some status information and those is lost after that.

**Comment by lscheffler** [comment]
Hi Doug,

I've tested a bit more. Setting up dump project with dumb hook to eleminate my code interfering.
What I see now:

- A project owns a project hook (just a hook with nothing in it)
- The project is part (sole or with other projects) of a solution
- The project is open (visible) on ProjectManager while ProjectExplorer is closing 

Unknown datasession remains
_VFP.OBJECTS holds nothing that points to this datasession

**Comment by DougHennig** [comment]
OK,I can reproduce this when at least one of the projects has a project hook. I'll see what I can figure out.

By the way, Project Explorer opens and closes a project at startup because it has to close the project in order to get version control information. However, it currently closes and reopens it twice so I'll change that so it only opens the project, closes it, and reopens it once at startup.

**Comment by DougHennig** [comment]
The latest release now opens, closes, and reopens the project at startup rather than open, close, open, close, open.

Although I can reproduce the unknown datasession issue, I have not been able to track down the cause. It definitely has something to do with the project hook so maybe it's a bug in VFP.

**Comment by lscheffler** [comment]
Possibly you should open the Projects in Datasession 1. Somehow VFP must handle the ProjectManager and I guess they do something behind the scenes.

Other akward way would be to close ProjectExplorer objects down and then close reopen the projects visible.

------------

For the source control stuff. 
Could you give me a hint what that does? I just have textfiles in git, so I see nothing that you could read there. The only reason to close the pjx I found is to generate / regenerate the text files for the project hooks ...

Edit 
.. and the pjx itself

**Comment by DougHennig** [comment]
I took your suggestions and opened the projects in the default datasession and that resolves the issue.

As for source control, Project Explorer has to close the project to generate text files for databases (if you do that) because they're held open and can't be closed while the project is open. Since I don't know if you're generating text files for databases (it's in the FoxBin2PRG configuration), it's just easier to close the project.

**Comment by lscheffler** [comment]
That's great.

For the source control, I understand the reason for (re)generating the files. (Thanks for pointing me to the DBC problem. Bin2Text ignores this.)
But opening the solution should do nothing regarding this. Or do you automatically sync text vs. binary? So I do not see why you close the projects on starting the solution.

**Comment by DougHennig** [comment]
When the solution is opened, it has to issue a Git/Hg command to get the current file status, and that requires the file to be closed.

**Comment by lscheffler** [comment]
But this is not true for only text files.

Anyway, how do you see what is valid? Do you see if I have to generate binary or text next?

With pure text, we add an additional layer to gits three-stage logic.
If I checkout out a different branch I can
-force text generation to bring this branch up to date, (Somehow cruel, but works),
-regenerate binary - even to single files/classes
-just check / compare something

This is more for my understanding. I think my way of working and thinking with git will never fit into your approach. :)

**Comment by DougHennig** [comment]
Project Explorer checks the status of all associated files of a binary file (for example, both the SCX and SCT files of a form) if Binary Only or Both is used or the text equivalent (for example, SC2 for a form) if Text Only or Both is used. So, I guess if you are using Text Only, it doesn't have to close the project. I fixed that in the latest release.
